[features]
seeds = false
skip-lint = false
[programs.devnet]
merklewhitelist = "5oKxBtfSUuyDQYQx3bMVpFTMZDJufPaKmtr8YnJSwpme"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/0xAckerman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
